/*primitive data types
--string
--numbers
--booleans
--null - empty value
--undefined -- declared variable without a value
--symbol -- unique value that can be generated by Symbol constructor
*/

/*non primitive data types
--arrays
--object
*/

/* rule of thumbs Non-primitive values (like objects, arrays, and functions)
 are compared by reference, not by value—so they are only 
strictly equal if they point to the exact same memory location.
*/

let nums = [1, 2, 3, 4]
let nums2 = nums
console.log(nums == nums2) //true


// Math Objects

const PI = Math.PI

console.log(PI)  // 3.141592653589793

console.log(Math.round(PI)) //3 -- rounds to nearest numbers
console.log(Math.round(9.85)) //10
console.log(Math.floor(PI)) //3 -- round down
console.log(Math.ceil(PI)) //4 -- round up

console.log(Math.min(-5, 3, 20, 4, 5, 10)) //-5 returns smallest value
console.log(Math.min(-5, 3, 20, 4, 5, 10)) //10 returns largest value


const randNum = Math.random() // creates random number between 0 to 0.999999
console.log(randNum);

const randNum1To10 = Math.ceil(Math.random() * 10) // creates random number between 1 and 10
console.log(randNum1To10)

const randNum0To10 = Math.floor(Math.random() * 11) // creates random number between 0 and 10
console.log(randNum0To10)

//absolute value
console.log(Math.abs(-10)) // 10 

//square root
console.log(Math.sqrt(100)) // 10 

console.log(Math.sqrt(2))       // 1.4142135623730951

//Power
console.log(Math.pow(3, 2))     // 9
console.log(Math.pow(5, 2))     // 25
console.log(Math.E)             //2.718281828459045

// Logarithm
// Returns the natural logarithm with base E of x, Math.log(x)
console.log(Math.log(2))        // 0.6931471805599453
console.log(Math.log(10))       // 2.302585092994046

// Returns the natural logarithm of 2 and 10 respectively
console.log(Math.LN2)           // 0.6931471805599453
console.log(Math.LN10)          // 2.302585092994046

//Trigonometry
console.log(Math.sin(0)) //0
console.log(Math.sin(60)) //--0.3048106211022167

console.log(Math.cos(0))   //1
console.log(Math.cos(60))  //-0.9524129804151563

//random generator 0-10

let random2 = Math.random()
let computeRandomness = Math.floor(random2 * 11)

console.log(computeRandomness)


//STRINGS=======================================================================================================

let space = ' '           // an empty space string
let firstName = 'Clarence Jake'
let lastName = 'Bonilla'
let country = 'Philippines'
let city = 'San Pablo'
let language = 'JavaScript'
let job = 'Business Apllication Developer'
let quote = "The saying,'Seeing is Believing' is not correct in 2020."
let quotWithBackTick = `The saying,'Seeing is Believing' is not correct in 2020.`
let age = 25

let fullName = firstName + space + lastName
console.log(fullName)
console.log('My name is ' + fullName + '. I live in ' + country + ' specifically in ' + city + '. I am ' + age + ' years old. ' + ' My current job is ' + job + '.')

const paragraph = "My name is Asabeneh Yetayeh. I live in Finland, Helsinki.\
I am a teacher and I love teaching. I teach HTML, CSS, JavaScript, React, Redux, \
Node.js, Python, Data Analysis and D3.js for anyone who is interested to learn. \
In the end of 2019, I was thinking to expand my teaching and to reach \
to global audience and I started a Python challenge from November 20 - December 19.\
It was one of the most rewarding and inspiring experience.\
Now, we are in 2020. I am enjoying preparing the 30DaysOfJavaScript challenge and \
I hope you are enjoying too."

console.log(paragraph)

/*
escape squence in string

\n: new line
\t: Tab, means 8 spaces
\\: Back slash
\': Single quote (')
\": Double quote (")

*/

console.log('I hope everyone is enjoying the 30 Days Of JavaScript challenge.\nDo you ?') // line break
console.log('Days\tTopics\tExercises') //Days  Topics  Exercises
console.log('Day 1\t3\t5') //Day 1 3 5
console.log('This is a backslash symbol (\\)') // This is a backslash  symbol (\)

//Template Literals (Templates Strings)
// `String literal text`
// `String literal text ${expression}`

let a = 10 
let b = 20

console.log(`The summation of ${a} and ${b} is ${a + b}`) //The summation of 10 and 20 is 30
console.log(`${a} is greater than ${b}: ${a > b}`) //10 is greater than 20: false

//string methods

//1.length

let js = 'Javascript'
console.log(js.length); //10

let firstName2 = 'Clarence'
console.log(firstName2.length) //8

//2.Accessing characters

let js2 = 'Javascript'
let firstLetter = js2[0]

console.log(firstLetter) //J
console.log(js2[1]) //a
console.log(js2[2]) //v

//3 toUpperCase()
console.log(js2.toUpperCase()) //JAVASCRIPT

//4 toLowerCase()
console.log(js2.toLowerCase()) //javascript

//5 substr() It takes two arguments, the starting index and number of characters to slice.
let string = 'JavaScript'
//index starts with 0 so J is 0
console.log(string.substr(4,6))    // Script

//6 substring(): It takes two arguments, the starting index and the stopping index but it doesn't include the character at the stopping index.

let string2 = 'JavaScript'
console.log(string2.substring(0,4)) //Java
console.log(string2.substring(4,10)) //Script

//7 split()
let string3 = '30 Days Of JavaScript'
console.log(string3.split())  // Changes to an array -> ["30 Days Of JavaScript"]
console.log(string3.split(' '))  [ '30', 'Days', 'Of', 'JavaScript' ]

let string4 ='Clarence'
console.log(string4.split('')) // Split to an array at each letter -> ['C', 'l', 'a', 'r', 'e', 'n', 'c', 'e']

let countries = 'Finland, Sweden, Norway, Denmark, and Iceland'
console.log(countries.split(','))  // split to any array at comma -> ["Finland", " Sweden", " Norway", " Denmark", " and Iceland"]
console.log(countries.split(', ')) //  ["Finland", "Sweden", "Norway", "Denmark", "and Iceland"]

//8 trim() --removes trailing spaces at the beginning or the end of the string

let string5 = '   30 Days Of JavaScript   '
console.log(string5)
console.log(string5.trim(' ')) //removes space at the beginning and the end
console.log(string5.trim())  // still removes spaces at the beginning and the end of the string

//9 include() returns a boolean. If a substring exist in a string, it returns true, otherwise it returns false. 
//CASE SENSITIVE

let string6 = '30 Days Of JavaScript'


console.log(string6.includes('Days'))     // true
console.log(string6.includes('days')) // false - case sensitive
console.log(string6.includes('Script'))   // true
console.log(string6.includes('script'))   // false
console.log(string6.includes('java'))     // false
console.log(string6.includes('Java'))     // true

//10 replace takes as a parameter the old substring and a new substring.
//CASE SENSITIVE
//string.replace(oldsubstring, newsubstring)

let string7 = '30 days of JavaScript'

console.log(string7.replace('JavaScript', 'Python'))

//11 charAt() Takes index and it returns the value at that index (also gets spaces)
//string.charAt(index)
//index start at 0

let string8 = '30 Days Of JavaScript'
console.log(string8.charAt(0)) //3

let getLastIndex = string8.length - 1
console.log(string8.charAt(getLastIndex)) //t

//12 charCodeAt()  Takes index and it returns char code (ASCII number) of the value at that index
 
let string9 = '30 Days Of JavaScript'
console.log(string.charCodeAt(3))   // D ASCII number is 68

let lastIndex = string9.length - 1
console.log(string.charCodeAt(lastIndex)) // t ASCII is 116

//13 indexOf(): Takes a substring and if the substring exists in a string it returns the first position else -1
//CASE SENSITIVE

let string10 = '30 Days Of JavaScript'

console.log(string10.indexOf('D'))          // 3
console.log(string10.indexOf('Days'))       // 3
console.log(string10.indexOf('a'))       // 4
console.log(string10.indexOf('A'))       // -1
console.log(string10.indexOf('JavaScript')) // 11
console.log(string10.indexOf('Script'))     //15
console.log(string10.indexOf('script'))     // -1

//14 lastIndexOf(): Takes a substring and if the substring exists in a string it returns the last position of the substring 
//else - 1
//CASE SENSITIVE


let string11 = 'I love JavaScript. If you do not love JavaScript what else can you love.'

console.log(string11.lastIndexOf('love')) //67 - last position is in index 67
console.log(string11.lastIndexOf('you'))  //63 - last position is in index 63
console.log(string11.lastIndexOf('l'))  //67
console.log(string11.lastIndexOf('y'))  //63


//15 concat(): it takes many substrings and joins them.

let string12 = '30'
let string13 = 'Days Of JavaScript'
let intoArray = string13.split(' ')

console.log(intoArray) //[ 'Days', 'Of', 'JavaScript' ]
console.log(string12.concat(intoArray[0], intoArray[1], intoArray[2])) 

let string15 = '30'
console.log(string15.concat("Days", "Of", "JavaScript")) // 30DaysOfJavaScript

//16 startsWith() : it takes a substring as an argument and it checks if the string starts with that specified substring. 
//returns true or false --- CASE SENSITIVE

//syntax
//string.startsWith(substring)

let string16 =  'Love is the best to in this world'

console.log(string16.startsWith('Love'))   // true
console.log(string16.startsWith('love'))   // false


//17 endsWith() : it takes a substring as an argument and it checks if the string starts with that specified substring. 
//returns true or false --- CASE SENSITIVE

//syntax
//string.endsWith(substring)

let string17  =  'Love is the best to in this world'

console.log(string16.startsWith('world'))   // true
console.log(string16.startsWith('World'))   // false
console.log(string16.startsWith('in this world'))   // true

/*18 search: it takes a substring as an argument and it returns the index of the first match. 
The search value can be a string or a regular expression pattern. */
//CASE SENSTITIVE

let string18 = 'I love JavaScript. If you do not love JavaScript what else can you love.'
console.log(string.search('love')) //2
console.log(string18.search(/javascript/gi)) // 7

/*
g -means search in the whole text
i -means case insensitive

*/

//19 match()
/*
match: it takes a substring or regular expression pattern 
as an argument and it returns an array if there is match if not it returns null. 
*/

let string20 = 'I love JavaScript. If you do not love JavaScript what else can you love.'
let patternOne = /love/     // with out any flag
let patternTwo = /love/gi   // g-means to search in the whole text, i - case insensitive

console.log(string20.match('love'))
/*
[
  'love',
  index: 0,
  input: 'I love JavaScript. If you do not love JavaScript what else can you love.',
  groups: undefined
]
*/
console.log(string20.match(/love/gi)) //[ 'love', 'love', 'love' ]

//extract number from text using regular expression
let txt = 'In 2019, I ran 30 Days of Python. Now, in 2020 I am super exited to start this challenge'
let regEx = /\d/g 
let regEx2 = /\d+/g
let regEx3 = /\d+/

// d with escape character means d not a normal d instead acts a digit
// + means one or more digit numbers,
// if there is g after that it means global, search everywhere.

console.log(txt.match(regEx)) //shows single digit numbers
/*[
  '2', '0', '1', '9',
  '3', '0', '2', '0',
  '2', '0'
] */

console.log(txt.match(regEx2)) //shows all more digit numbers
//[ '2019', '30', '2020' ]

console.log(txt.match(regEx3)) // shows first more digit numbers
/*
[
  '2019',
  index: 3,
  input: 'In 2019, I ran 30 Days of Python. Now, in 2020 I am super exited to start this challenge',
  groups: undefined
] */

//20 repat() it takes a number as argument and it returns the repeated version of the string.
let string21 = 'love'
console.log(string21.repeat(10)) //lovelovelovelovelovelovelovelovelovelove

//DATA TYPES AND CASTING

// Different javascript data types
// Let's declare different data types

let firstName3 = 'Clarence Jake'     // string
let lastName3 = 'Bonilla'           // string
let country3 = 'Philippines'       // string
let city3 = 'San Pablo'           // string
let age3 = 24                    // number, it is not my real age, do not worry about it
let job3    // undefined, because a value was not assigned

console.log(typeof 'Clarence Jake')  // string
console.log(typeof firstName3)   // string
console.log(typeof 10)          // number
console.log(typeof 3.14)        // number
console.log(typeof true)        // boolean
console.log(typeof false)       // boolean
console.log(typeof NaN)         // number
console.log(typeof job3)         // undefined
console.log(typeof undefined)   // undefined
console.log(typeof null)        // object


//CHANGING DATA TYPE (CASTING)
//Casting: Converting one data type to another data type. We use parseInt(), parseFloat(), Number(), + sign, str()

//String to Int
let num = '20'
let  numToInt = parseInt(num)
console.log(numToInt) //20
console.log(typeof num) //string
console.log(typeof numToInt) //number

let num2 = '20'
let  numToInt2 = Number(num)
console.log(numToInt) //20

let num3 = '10'
let numInt3 = +num3

console.log(numInt3) // 10


//String to float

let num4 = '9.81'
let numFloat = parseFloat(num4)

console.log(numFloat) // 9.81


let num5 = '9.81'
let numFloat5 = Number(num5)

console.log(numFloat5) // 9.81

let num6 = '9.81'
let numFloat6 = +num6

console.log(numFloat6) // 9.81

//FLOAT TO INT

let numf = 9.81
let numInt = parseInt(numf)

console.log(numInt) // 9

























































