/*primitive data types
--string
--numbers
--booleans
--null - empty value
--undefined -- declared variable without a value
--symbol -- unique value that can be generated by Symbol constructor
*/

/*non primitive data types
--arrays
--object
*/

/* rule of thumbs Non-primitive values (like objects, arrays, and functions)
 are compared by reference, not by value—so they are only 
strictly equal if they point to the exact same memory location.
*/

let nums = [1, 2, 3, 4]
let nums2 = nums
console.log(nums == nums2) //true


// Math Objects

const PI = Math.PI

console.log(PI)  // 3.141592653589793

console.log(Math.round(PI)) //3 -- rounds to nearest numbers
console.log(Math.round(9.85)) //10
console.log(Math.floor(PI)) //3 -- round down
console.log(Math.ceil(PI)) //4 -- round up

console.log(Math.min(-5, 3, 20, 4, 5, 10)) //-5 returns smallest value
console.log(Math.min(-5, 3, 20, 4, 5, 10)) //10 returns largest value


const randNum = Math.random() // creates random number between 0 to 0.999999
console.log(randNum);

const randNum1To10 = Math.ceil(Math.random() * 10) // creates random number between 1 and 10
console.log(randNum1To10)

const randNum0To10 = Math.floor(Math.random() * 11) // creates random number between 0 and 10
console.log(randNum0To10)

//absolute value
console.log(Math.abs(-10)) // 10 

//square root
console.log(Math.sqrt(100)) // 10 

console.log(Math.sqrt(2))       // 1.4142135623730951

console.log(Math.pow(3, 2))     // 9

console.log(Math.pow(5, 2))     // 25

